spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:

      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_image?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: nhanbn98

server:
  port: 9001
